// Categorized list of ingredients with emojis
// Expanded for global representation

const ingredients = {
  fruits: [
    { name: "Apple", emoji: "🍎", icon: "apple", iconSet: "MaterialCommunityIcons" },
    { name: "Banana", emoji: "🍌", icon: "fruit-banana", iconSet: "MaterialCommunityIcons" },
    { name: "Orange", emoji: "🍊", icon: "fruit-citrus", iconSet: "MaterialCommunityIcons" },
    { name: "Strawberry", emoji: "🍓", icon: "fruit-strawberry", iconSet: "MaterialCommunityIcons" },
    { name: "Grapes", emoji: "🍇", icon: "fruit-grapes", iconSet: "MaterialCommunityIcons" },
    { name: "Pineapple", emoji: "🍍", icon: "pineapple", iconSet: "MaterialCommunityIcons" },
    { name: "Watermelon", emoji: "🍉", icon: "fruit-watermelon", iconSet: "MaterialCommunityIcons" },
    { name: "Lemon", emoji: "🍋", icon: "fruit-citrus", iconSet: "MaterialCommunityIcons" },
    { name: "Peach", emoji: "🍑", icon: "fruit-peach", iconSet: "MaterialCommunityIcons" },
    { name: "Mango", emoji: "🥭", icon: "fruit-mango", iconSet: "MaterialCommunityIcons" },
    { name: "Avocado", emoji: "🥑", icon: "fruit-avocado", iconSet: "MaterialCommunityIcons" },
    { name: "Coconut", emoji: "🥥", icon: "fruit-coconut", iconSet: "MaterialCommunityIcons" },
    { name: "Kiwi", emoji: "🥝", icon: "fruit-kiwi", iconSet: "MaterialCommunityIcons" },
    { name: "Blueberry", emoji: "🫐", icon: "fruit-berries", iconSet: "MaterialCommunityIcons" },
    { name: "Melon", emoji: "🍈", icon: "fruit-watermelon", iconSet: "MaterialCommunityIcons" },
    { name: "Pear", emoji: "🍐", icon: "fruit-pear", iconSet: "MaterialCommunityIcons" },
    { name: "Plum", emoji: "🍑", icon: "fruit-pear", iconSet: "MaterialCommunityIcons" },
    { name: "Fig", emoji: "🫒", icon: "fruit-pear", iconSet: "MaterialCommunityIcons" },
    { name: "Pomegranate", emoji: "🍎", icon: "fruit-pomegranate", iconSet: "MaterialCommunityIcons" },
    { name: "Guava", emoji: "🥝", icon: "fruit-pear", iconSet: "MaterialCommunityIcons" },
    { name: "Papaya", emoji: "🥭", icon: "fruit-papaya", iconSet: "MaterialCommunityIcons" },
    { name: "Raspberry", emoji: "🍓", icon: "fruit-raspberry", iconSet: "MaterialCommunityIcons" },
    { name: "Blackberry", emoji: "🫐", icon: "fruit-berries", iconSet: "MaterialCommunityIcons" },
    { name: "Starfruit", emoji: "⭐", icon: "star", iconSet: "MaterialCommunityIcons" },
    { name: "Dragon Fruit", emoji: "🐉", icon: "dragon", iconSet: "MaterialCommunityIcons" },
    { name: "Date", emoji: "🌴", icon: "fruit-pear", iconSet: "MaterialCommunityIcons" },
    { name: "Soursop", emoji: "🥝", icon: "fruit-pear", iconSet: "MaterialCommunityIcons" },
    { name: "Persimmon", emoji: "🍊", icon: "fruit-pear", iconSet: "MaterialCommunityIcons" },
    { name: "Gooseberry", emoji: "🫐", icon: "fruit-berries", iconSet: "MaterialCommunityIcons" },
    { name: "Currant", emoji: "🫐", icon: "fruit-berries", iconSet: "MaterialCommunityIcons" },
  ],
  exotic_fruits: [
    { name: "Rambutan", emoji: "🍒" },
    { name: "Salak (Snake Fruit)", emoji: "🥭" },
    { name: "Mangosteen", emoji: "🍈" },
    { name: "Sapote", emoji: "🥭" },
    { name: "Atemoya", emoji: "🍈" },
    { name: "Miracle Fruit", emoji: "🍒" },
    { name: "Jabuticaba", emoji: "🍇" },
    { name: "Ackee", emoji: "🍈" },
    { name: "Breadfruit", emoji: "🍞" },
    { name: "Baobab Fruit", emoji: "🌳" },
    { name: "Horned Melon", emoji: "🍈" },
    { name: "Feijoa", emoji: "🥝" },
    { name: "Cherimoya", emoji: "🍈" },
    { name: "Medlar", emoji: "🍎" },
    { name: "Marang", emoji: "🥭" },
  ],
  vegetables: [
    { name: "Carrot", emoji: "🥕", icon: "carrot", iconSet: "MaterialCommunityIcons" },
    { name: "Broccoli", emoji: "🥦", icon: "food-variant", iconSet: "MaterialCommunityIcons" },
    { name: "Corn", emoji: "🌽", icon: "corn", iconSet: "MaterialCommunityIcons" },
    { name: "Tomato", emoji: "🍅", icon: "food-apple", iconSet: "MaterialCommunityIcons" },
    { name: "Potato", emoji: "🥔", icon: "potato", iconSet: "MaterialCommunityIcons" },
    { name: "Cucumber", emoji: "🥒", icon: "food-apple-outline", iconSet: "MaterialCommunityIcons" },
    { name: "Eggplant", emoji: "🍆", icon: "eggplant", iconSet: "MaterialCommunityIcons" },
    { name: "Onion", emoji: "🧅", icon: "onion", iconSet: "MaterialCommunityIcons" },
    { name: "Garlic", emoji: "🧄", icon: "garlic", iconSet: "MaterialCommunityIcons" },
    { name: "Lettuce", emoji: "🥬", icon: "leaf", iconSet: "MaterialCommunityIcons" },
    { name: "Pepper", emoji: "🫑", icon: "chili-mild", iconSet: "MaterialCommunityIcons" },
    { name: "Mushroom", emoji: "🍄" },
    { name: "Sweet Potato", emoji: "🍠", icon: "food-apple", iconSet: "MaterialCommunityIcons" },
    { name: "Chili Pepper", emoji: "🌶️", icon: "chili-mild", iconSet: "MaterialCommunityIcons" },
    { name: "Peas", emoji: "🫛", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Okra", emoji: "🫛", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Zucchini", emoji: "🥒", icon: "food-apple-outline", iconSet: "MaterialCommunityIcons" },
    { name: "Radish", emoji: "��️", icon: "radish", iconSet: "MaterialCommunityIcons" },
    { name: "Turnip", emoji: "🍠", icon: "turnip", iconSet: "MaterialCommunityIcons" },
    { name: "Artichoke", emoji: "🥬", icon: "food-apple", iconSet: "MaterialCommunityIcons" },
    { name: "Fennel", emoji: "🥬", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Leek", emoji: "🥬", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Celery", emoji: "🥬", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Kale", emoji: "🥬", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Spinach", emoji: "🥬", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Bok Choy", emoji: "🥬", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Daikon", emoji: "🌶️", icon: "radish", iconSet: "MaterialCommunityIcons" },
    { name: "Yam", emoji: "🍠", icon: "food-apple", iconSet: "MaterialCommunityIcons" },
    { name: "Cassava", emoji: "🍠", icon: "food-apple", iconSet: "MaterialCommunityIcons" },
    { name: "Jicama", emoji: "🍠", icon: "food-apple", iconSet: "MaterialCommunityIcons" },
    { name: "Taro", emoji: "🍠", icon: "food-apple", iconSet: "MaterialCommunityIcons" },
    { name: "Lotus Root", emoji: "🍠", icon: "lotus", iconSet: "MaterialCommunityIcons" },
    { name: "Cabbage", emoji: "🥬", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Brussels Sprouts", emoji: "🥦", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Pumpkin", emoji: "🎃", icon: "pumpkin", iconSet: "MaterialCommunityIcons" },
    { name: "Squash", emoji: "🎃", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Chayote", emoji: "🥒", icon: "food-apple-outline", iconSet: "MaterialCommunityIcons" },
    { name: "Endive", emoji: "🥬", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Rutabaga", emoji: "🍠", icon: "food-apple", iconSet: "MaterialCommunityIcons" },
  ],
  tubers: [
    { name: "Potato", emoji: "🥔", icon: "potato", iconSet: "MaterialCommunityIcons" },
    { name: "Sweet Potato", emoji: "🍠", icon: "food-apple", iconSet: "MaterialCommunityIcons" },
    { name: "Yam", emoji: "🍠", icon: "food-apple", iconSet: "MaterialCommunityIcons" },
    { name: "Cassava", emoji: "🍠", icon: "food-apple", iconSet: "MaterialCommunityIcons" },
    { name: "Taro", emoji: "🍠", icon: "food-apple", iconSet: "MaterialCommunityIcons" },
    { name: "Jicama", emoji: "🍠", icon: "food-apple", iconSet: "MaterialCommunityIcons" },
    { name: "Lotus Root", emoji: "🍠", icon: "lotus", iconSet: "MaterialCommunityIcons" },
    { name: "Rutabaga", emoji: "🍠", icon: "food-apple", iconSet: "MaterialCommunityIcons" },
    { name: "Parsnip", emoji: "🥕", icon: "carrot", iconSet: "MaterialCommunityIcons" },
    { name: "Sunchoke", emoji: "🍠", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
  ],
  sea_vegetables: [
    { name: "Nori", emoji: "🌊", icon: "leaf", iconSet: "MaterialCommunityIcons" },
    { name: "Wakame", emoji: "🌊", icon: "leaf", iconSet: "MaterialCommunityIcons" },
    { name: "Kombu", emoji: "🌊", icon: "leaf", iconSet: "MaterialCommunityIcons" },
    { name: "Dulse", emoji: "🌊", icon: "leaf", iconSet: "MaterialCommunityIcons" },
    { name: "Hijiki", emoji: "🌊", icon: "leaf", iconSet: "MaterialCommunityIcons" },
    { name: "Sea Lettuce", emoji: "🌊", icon: "leaf", iconSet: "MaterialCommunityIcons" },
    { name: "Irish Moss", emoji: "🌊", icon: "leaf", iconSet: "MaterialCommunityIcons" },
  ],
  mushrooms: [
    { name: "Button Mushroom", emoji: "🍄", icon: "mushroom", iconSet: "MaterialCommunityIcons" },
    { name: "Shiitake", emoji: "🍄", icon: "mushroom", iconSet: "MaterialCommunityIcons" },
    { name: "Oyster Mushroom", emoji: "🍄", icon: "mushroom", iconSet: "MaterialCommunityIcons" },
    { name: "Portobello", emoji: "🍄", icon: "mushroom", iconSet: "MaterialCommunityIcons" },
    { name: "Enoki", emoji: "🍄", icon: "mushroom", iconSet: "MaterialCommunityIcons" },
    { name: "Morel", emoji: "🍄", icon: "mushroom", iconSet: "MaterialCommunityIcons" },
    { name: "Chanterelle", emoji: "🍄", icon: "mushroom", iconSet: "MaterialCommunityIcons" },
    { name: "Porcini", emoji: "🍄", icon: "mushroom", iconSet: "MaterialCommunityIcons" },
    { name: "Maitake", emoji: "🍄", icon: "mushroom", iconSet: "MaterialCommunityIcons" },
    { name: "King Oyster", emoji: "🍄", icon: "mushroom", iconSet: "MaterialCommunityIcons" },
    { name: "Truffle", emoji: "🍄", icon: "mushroom", iconSet: "MaterialCommunityIcons" },
  ],
  meats: [
    { name: "Chicken", emoji: "🍗", icon: "food-drumstick", iconSet: "MaterialCommunityIcons" },
    { name: "Beef", emoji: "🥩", icon: "cow", iconSet: "MaterialCommunityIcons" },
    { name: "Pork", emoji: "🍖", icon: "pig", iconSet: "MaterialCommunityIcons" },
    { name: "Bacon", emoji: "🥓", icon: "food-bacon", iconSet: "MaterialCommunityIcons" },
    { name: "Lamb", emoji: "🍖", icon: "cow", iconSet: "MaterialCommunityIcons" },
    { name: "Turkey", emoji: "🦃", icon: "turkey", iconSet: "MaterialCommunityIcons" },
    { name: "Duck", emoji: "🦆", icon: "duck", iconSet: "MaterialCommunityIcons" },
    { name: "Sausage", emoji: "🌭", icon: "food-hotdog", iconSet: "MaterialCommunityIcons" },
    { name: "Goat", emoji: "🐐", icon: "goat", iconSet: "MaterialCommunityIcons" },
    { name: "Rabbit", emoji: "🐇", icon: "rabbit", iconSet: "MaterialCommunityIcons" },
    { name: "Venison", emoji: "🦌", icon: "deer", iconSet: "MaterialCommunityIcons" },
    { name: "Quail", emoji: "🐦", icon: "bird", iconSet: "MaterialCommunityIcons" },
    { name: "Pigeon", emoji: "🐦", icon: "bird", iconSet: "MaterialCommunityIcons" },
    { name: "Kangaroo", emoji: "🦘", icon: "kangaroo", iconSet: "MaterialCommunityIcons" },
    { name: "Buffalo", emoji: "🐃", icon: "buffalo", iconSet: "MaterialCommunityIcons" },
    { name: "Camel", emoji: "🐪", icon: "camel", iconSet: "MaterialCommunityIcons" },
    { name: "Frog", emoji: "🐸", icon: "frog", iconSet: "MaterialCommunityIcons" },
    { name: "Alligator", emoji: "🐊", icon: "alligator", iconSet: "MaterialCommunityIcons" },
  ],
  seafood: [
    { name: "Fish", emoji: "🐟", icon: "fish", iconSet: "MaterialCommunityIcons" },
    { name: "Shrimp", emoji: "🦐", icon: "shrimp", iconSet: "MaterialCommunityIcons" },
    { name: "Crab", emoji: "🦀", icon: "crab", iconSet: "MaterialCommunityIcons" },
    { name: "Lobster", emoji: "��", icon: "lobster", iconSet: "MaterialCommunityIcons" },
    { name: "Octopus", emoji: "🐙", icon: "octopus", iconSet: "MaterialCommunityIcons" },
    { name: "Squid", emoji: "🦑", icon: "squid", iconSet: "MaterialCommunityIcons" },
    { name: "Oyster", emoji: "🦪", icon: "oyster", iconSet: "MaterialCommunityIcons" },
    { name: "Scallop", emoji: "��", icon: "scallop", iconSet: "MaterialCommunityIcons" },
    { name: "Sushi", emoji: "🍣", icon: "sushi", iconSet: "MaterialCommunityIcons" },
    { name: "Clam", emoji: "🦪", icon: "clam", iconSet: "MaterialCommunityIcons" },
    { name: "Mussel", emoji: "🦪", icon: "mussel", iconSet: "MaterialCommunityIcons" },
    { name: "Anchovy", emoji: "🐟", icon: "fish", iconSet: "MaterialCommunityIcons" },
    { name: "Sardine", emoji: "🐟", icon: "fish", iconSet: "MaterialCommunityIcons" },
    { name: "Eel", emoji: "🐍", icon: "fish", iconSet: "MaterialCommunityIcons" },
    { name: "Caviar", emoji: "🍥", icon: "fish", iconSet: "MaterialCommunityIcons" },
    { name: "Sea Urchin", emoji: "🌊", icon: "sea-urchin", iconSet: "MaterialCommunityIcons" },
    { name: "Abalone", emoji: "🦪", icon: "abalone", iconSet: "MaterialCommunityIcons" },
  ],
  dairy: [
    { name: "Milk", emoji: "🥛", icon: "glass-mug-variant", iconSet: "MaterialCommunityIcons" },
    { name: "Cheese", emoji: "🧀", icon: "cheese", iconSet: "MaterialCommunityIcons" },
    { name: "Butter", emoji: "🧈", icon: "butterfly", iconSet: "MaterialCommunityIcons" },
    { name: "Yogurt", emoji: "🥣", icon: "yogurt", iconSet: "MaterialCommunityIcons" },
    { name: "Cream", emoji: "🥛", icon: "food-egg-easter", iconSet: "MaterialCommunityIcons" },
    { name: "Egg", emoji: "🥚", icon: "egg", iconSet: "MaterialCommunityIcons" },
    { name: "Ice Cream", emoji: "🍨", icon: "ice-cream", iconSet: "MaterialCommunityIcons" },
    { name: "Ghee", emoji: "🧈", icon: "butterfly", iconSet: "MaterialCommunityIcons" },
    { name: "Condensed Milk", emoji: "🥛", icon: "glass-mug-variant", iconSet: "MaterialCommunityIcons" },
    { name: "Evaporated Milk", emoji: "🥛", icon: "glass-mug-variant", iconSet: "MaterialCommunityIcons" },
    { name: "Sour Cream", emoji: "🥛", icon: "food-egg-easter", iconSet: "MaterialCommunityIcons" },
    { name: "Kefir", emoji: "🥛", icon: "yogurt", iconSet: "MaterialCommunityIcons" },
    { name: "Paneer", emoji: "🧀", icon: "cheese", iconSet: "MaterialCommunityIcons" },
    { name: "Ricotta", emoji: "🧀", icon: "cheese", iconSet: "MaterialCommunityIcons" },
    { name: "Mascarpone", emoji: "🧀", icon: "cheese", iconSet: "MaterialCommunityIcons" },
  ],
  cheeses: [
    { name: "Cheddar", emoji: "🧀", icon: "cheese", iconSet: "MaterialCommunityIcons" },
    { name: "Mozzarella", emoji: "🧀", icon: "cheese", iconSet: "MaterialCommunityIcons" },
    { name: "Parmesan", emoji: "🧀", icon: "cheese", iconSet: "MaterialCommunityIcons" },
    { name: "Feta", emoji: "🧀", icon: "cheese", iconSet: "MaterialCommunityIcons" },
    { name: "Brie", emoji: "🧀", icon: "cheese", iconSet: "MaterialCommunityIcons" },
    { name: "Camembert", emoji: "🧀", icon: "cheese", iconSet: "MaterialCommunityIcons" },
    { name: "Gouda", emoji: "🧀", icon: "cheese", iconSet: "MaterialCommunityIcons" },
    { name: "Swiss", emoji: "🧀", icon: "cheese", iconSet: "MaterialCommunityIcons" },
    { name: "Blue Cheese", emoji: "🧀", icon: "cheese", iconSet: "MaterialCommunityIcons" },
    { name: "Goat Cheese", emoji: "🧀", icon: "cheese", iconSet: "MaterialCommunityIcons" },
    { name: "Halloumi", emoji: "🧀", icon: "cheese", iconSet: "MaterialCommunityIcons" },
    { name: "Manchego", emoji: "🧀", icon: "cheese", iconSet: "MaterialCommunityIcons" },
    { name: "Gruyère", emoji: "🧀", icon: "cheese", iconSet: "MaterialCommunityIcons" },
    { name: "Provolone", emoji: "🧀", icon: "cheese", iconSet: "MaterialCommunityIcons" },
    { name: "Queso Fresco", emoji: "🧀", icon: "cheese", iconSet: "MaterialCommunityIcons" },
    { name: "Paneer", emoji: "🧀", icon: "cheese", iconSet: "MaterialCommunityIcons" },
    { name: "Ricotta", emoji: "🧀", icon: "cheese", iconSet: "MaterialCommunityIcons" },
    { name: "Mascarpone", emoji: "🧀", icon: "cheese", iconSet: "MaterialCommunityIcons" },
    { name: "Cottage Cheese", emoji: "🧀", icon: "cheese", iconSet: "MaterialCommunityIcons" },
  ],
  grains: [
    { name: "Rice", emoji: "🍚", icon: "rice", iconSet: "MaterialCommunityIcons" },
    { name: "Bread", emoji: "🍞", icon: "bread-slice", iconSet: "MaterialCommunityIcons" },
    { name: "Pasta", emoji: "🍝", icon: "noodles", iconSet: "MaterialCommunityIcons" },
    { name: "Noodles", emoji: "🍜", icon: "noodles", iconSet: "MaterialCommunityIcons" },
    { name: "Tortilla", emoji: "🌮", icon: "tortilla", iconSet: "MaterialCommunityIcons" },
    { name: "Oats", emoji: "🌾", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Cornflakes", emoji: "🥣", icon: "corn", iconSet: "MaterialCommunityIcons" },
    { name: "Quinoa", emoji: "🌾", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Barley", emoji: "🌾", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Millet", emoji: "🌾", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Buckwheat", emoji: "🌾", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Sorghum", emoji: "🌾", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Rye", emoji: "🌾", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Couscous", emoji: "🍚", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Polenta", emoji: "🍚", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Farro", emoji: "🌾", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Teff", emoji: "🌾", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Freekeh", emoji: "🌾", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Amaranth", emoji: "🌾", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
  ],
  breads: [
    { name: "Baguette", emoji: "🥖", icon: "bread-slice", iconSet: "MaterialCommunityIcons" },
    { name: "Sourdough", emoji: "🍞", icon: "bread-slice", iconSet: "MaterialCommunityIcons" },
    { name: "Pita", emoji: "🫓", icon: "bread-slice", iconSet: "MaterialCommunityIcons" },
    { name: "Naan", emoji: "🫓", icon: "bread-slice", iconSet: "MaterialCommunityIcons" },
    { name: "Rye Bread", emoji: "🍞", icon: "bread-slice", iconSet: "MaterialCommunityIcons" },
    { name: "Ciabatta", emoji: "🍞", icon: "bread-slice", iconSet: "MaterialCommunityIcons" },
    { name: "Focaccia", emoji: "🍞", icon: "bread-slice", iconSet: "MaterialCommunityIcons" },
    { name: "Challah", emoji: "🍞", icon: "bread-slice", iconSet: "MaterialCommunityIcons" },
    { name: "Brioche", emoji: "🍞", icon: "bread-slice", iconSet: "MaterialCommunityIcons" },
    { name: "Cornbread", emoji: "🍞", icon: "bread-slice", iconSet: "MaterialCommunityIcons" },
    { name: "Tortilla", emoji: "🌮", icon: "tortilla", iconSet: "MaterialCommunityIcons" },
    { name: "Lavash", emoji: "🫓", icon: "bread-slice", iconSet: "MaterialCommunityIcons" },
    { name: "Injera", emoji: "🫓", icon: "bread-slice", iconSet: "MaterialCommunityIcons" },
    { name: "Matzo", emoji: "🍞", icon: "bread-slice", iconSet: "MaterialCommunityIcons" },
    { name: "Paratha", emoji: "🫓", icon: "bread-slice", iconSet: "MaterialCommunityIcons" },
    { name: "Roti", emoji: "🫓", icon: "bread-slice", iconSet: "MaterialCommunityIcons" },
    { name: "Bun", emoji: "🍔", icon: "food-bread-variant", iconSet: "MaterialCommunityIcons" },
    { name: "Pretzel", emoji: "🥨", icon: "food-bread-variant", iconSet: "MaterialCommunityIcons" },
    { name: "Bagel", emoji: "🥯", icon: "food-bread-variant", iconSet: "MaterialCommunityIcons" },
  ],
  legumes: [
    { name: "Beans", emoji: "🫘", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Lentils", emoji: "🫘", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Chickpeas", emoji: "🧆", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Peanuts", emoji: "🥜", icon: "food-nut", iconSet: "MaterialCommunityIcons" },
    { name: "Soybeans", emoji: "🫘", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Black Beans", emoji: "🫘", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Kidney Beans", emoji: "🫘", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Navy Beans", emoji: "🫘", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Pinto Beans", emoji: "🫘", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Mung Beans", emoji: "🫘", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Fava Beans", emoji: "🫘", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Lima Beans", emoji: "🫘", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Green Peas", emoji: "🫛", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Split Peas", emoji: "🫛", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
  ],
  nuts_and_seeds: [
    { name: "Almond", emoji: "🌰", icon: "nut", iconSet: "MaterialCommunityIcons" },
    { name: "Walnut", emoji: "🌰", icon: "nut", iconSet: "MaterialCommunityIcons" },
    { name: "Cashew", emoji: "🥜", icon: "nut", iconSet: "MaterialCommunityIcons" },
    { name: "Pistachio", emoji: "🥜", icon: "nut", iconSet: "MaterialCommunityIcons" },
    { name: "Sunflower Seeds", emoji: "🌻", icon: "flower", iconSet: "MaterialCommunityIcons" },
    { name: "Pumpkin Seeds", emoji: "🎃", icon: "pumpkin", iconSet: "MaterialCommunityIcons" },
    { name: "Sesame Seeds", emoji: "🌱", icon: "nut", iconSet: "MaterialCommunityIcons" },
    { name: "Hazelnut", emoji: "🌰", icon: "nut", iconSet: "MaterialCommunityIcons" },
    { name: "Pecan", emoji: "🌰", icon: "nut", iconSet: "MaterialCommunityIcons" },
    { name: "Macadamia", emoji: "🌰", icon: "nut", iconSet: "MaterialCommunityIcons" },
    { name: "Pine Nut", emoji: "🌲", icon: "pine-tree", iconSet: "MaterialCommunityIcons" },
    { name: "Brazil Nut", emoji: "🌰", icon: "nut", iconSet: "MaterialCommunityIcons" },
    { name: "Chestnut", emoji: "🌰", icon: "nut", iconSet: "MaterialCommunityIcons" },
    { name: "Chia Seeds", emoji: "🌱", icon: "nut", iconSet: "MaterialCommunityIcons" },
    { name: "Flax Seeds", emoji: "🌱", icon: "nut", iconSet: "MaterialCommunityIcons" },
    { name: "Hemp Seeds", emoji: "🌱", icon: "nut", iconSet: "MaterialCommunityIcons" },
    { name: "Watermelon Seeds", emoji: "🍉", icon: "watermelon", iconSet: "MaterialCommunityIcons" },
  ],
  herbs_and_spices: [
    { name: "Basil", emoji: "🌿", icon: "leaf", iconSet: "MaterialCommunityIcons" },
    { name: "Parsley", emoji: "🌿", icon: "leaf", iconSet: "MaterialCommunityIcons" },
    { name: "Cilantro", emoji: "🌿", icon: "leaf", iconSet: "MaterialCommunityIcons" },
    { name: "Rosemary", emoji: "🌿", icon: "leaf", iconSet: "MaterialCommunityIcons" },
    { name: "Thyme", emoji: "🌿", icon: "leaf", iconSet: "MaterialCommunityIcons" },
    { name: "Mint", emoji: "🌿", icon: "leaf", iconSet: "MaterialCommunityIcons" },
    { name: "Oregano", emoji: "🌿", icon: "leaf", iconSet: "MaterialCommunityIcons" },
    { name: "Sage", emoji: "🌿", icon: "leaf", iconSet: "MaterialCommunityIcons" },
    { name: "Cinnamon", emoji: "🌰", icon: "cinnamon", iconSet: "MaterialCommunityIcons" },
    { name: "Ginger", emoji: "🫚", icon: "ginger", iconSet: "MaterialCommunityIcons" },
    { name: "Turmeric", emoji: "🟧", icon: "turmeric", iconSet: "MaterialCommunityIcons" },
    { name: "Pepper", emoji: "🌶️", icon: "pepper", iconSet: "MaterialCommunityIcons" },
    { name: "Salt", emoji: "🧂", icon: "shaker-outline", iconSet: "MaterialCommunityIcons" },
    { name: "Chili", emoji: "🌶️", icon: "pepper", iconSet: "MaterialCommunityIcons" },
    { name: "Clove", emoji: "🌰", icon: "nut", iconSet: "MaterialCommunityIcons" },
    { name: "Nutmeg", emoji: "🌰", icon: "nut", iconSet: "MaterialCommunityIcons" },
    { name: "Cardamom", emoji: "🌰", icon: "nut", iconSet: "MaterialCommunityIcons" },
    { name: "Bay Leaf", emoji: "🌿", icon: "leaf", iconSet: "MaterialCommunityIcons" },
    { name: "Dill", emoji: "🌿", icon: "leaf", iconSet: "MaterialCommunityIcons" },
    { name: "Tarragon", emoji: "🌿", icon: "leaf", iconSet: "MaterialCommunityIcons" },
    { name: "Coriander", emoji: "🌿", icon: "leaf", iconSet: "MaterialCommunityIcons" },
    { name: "Saffron", emoji: "🧡", icon: "saffron", iconSet: "MaterialCommunityIcons" },
    { name: "Paprika", emoji: "🌶️", icon: "pepper", iconSet: "MaterialCommunityIcons" },
    { name: "Curry Leaf", emoji: "🌿", icon: "leaf", iconSet: "MaterialCommunityIcons" },
    { name: "Fenugreek", emoji: "🌿", icon: "leaf", iconSet: "MaterialCommunityIcons" },
    { name: "Wasabi", emoji: "🌱", icon: "wasabi", iconSet: "MaterialCommunityIcons" },
    { name: "Galangal", emoji: "🫚", icon: "ginger", iconSet: "MaterialCommunityIcons" },
    { name: "Star Anise", emoji: "⭐", icon: "star", iconSet: "MaterialCommunityIcons" },
    { name: "Sumac", emoji: "🌿", icon: "nut", iconSet: "MaterialCommunityIcons" },
    { name: "Za'atar", emoji: "🌿", icon: "nut", iconSet: "MaterialCommunityIcons" },
  ],
  oils_and_fats: [
    { name: "Olive Oil", emoji: "🫒", icon: "olive-oil", iconSet: "MaterialCommunityIcons" },
    { name: "Vegetable Oil", emoji: "🛢️", icon: "oil", iconSet: "MaterialCommunityIcons" },
    { name: "Coconut Oil", emoji: "🥥", icon: "coconut-oil", iconSet: "MaterialCommunityIcons" },
    { name: "Butter", emoji: "🧈", icon: "butterfly", iconSet: "MaterialCommunityIcons" },
    { name: "Lard", emoji: "🍖", icon: "pig", iconSet: "MaterialCommunityIcons" },
    { name: "Ghee", emoji: "🧈", icon: "butterfly", iconSet: "MaterialCommunityIcons" },
    { name: "Sesame Oil", emoji: "🌱", icon: "nut", iconSet: "MaterialCommunityIcons" },
    { name: "Peanut Oil", emoji: "🥜", icon: "nut", iconSet: "MaterialCommunityIcons" },
    { name: "Sunflower Oil", emoji: "🌻", icon: "sunflower", iconSet: "MaterialCommunityIcons" },
    { name: "Palm Oil", emoji: "🌴", icon: "palm-tree", iconSet: "MaterialCommunityIcons" },
    { name: "Canola Oil", emoji: "🌱", icon: "nut", iconSet: "MaterialCommunityIcons" },
    { name: "Avocado Oil", emoji: "🥑", icon: "avocado", iconSet: "MaterialCommunityIcons" },
    { name: "Corn Oil", emoji: "🌽", icon: "corn", iconSet: "MaterialCommunityIcons" },
    { name: "Soybean Oil", emoji: "🫘", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
  ],
  condiments: [
    { name: "Ketchup", emoji: "🍅", icon: "ketchup", iconSet: "MaterialCommunityIcons" },
    { name: "Mayonnaise", emoji: "🥪", icon: "food-egg-easter", iconSet: "MaterialCommunityIcons" },
    { name: "Mustard", emoji: "🌭", icon: "food-hotdog", iconSet: "MaterialCommunityIcons" },
    { name: "Soy Sauce", emoji: "🥢", icon: "food-salt", iconSet: "MaterialCommunityIcons" },
    { name: "Vinegar", emoji: "🍶", icon: "vinegar", iconSet: "MaterialCommunityIcons" },
    { name: "Hot Sauce", emoji: "🌶️", icon: "pepper", iconSet: "MaterialCommunityIcons" },
    { name: "Barbecue Sauce", emoji: "🍖", icon: "food-hamburger", iconSet: "MaterialCommunityIcons" },
    { name: "Honey", emoji: "🍯", icon: "honey-pot", iconSet: "MaterialCommunityIcons" },
    { name: "Jam", emoji: "🍓", icon: "food-fruit-grapes", iconSet: "MaterialCommunityIcons" },
    { name: "Maple Syrup", emoji: "🍁", icon: "maple-syrup", iconSet: "MaterialCommunityIcons" },
    { name: "Chutney", emoji: "🥣", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
    { name: "Relish", emoji: "🥒", icon: "food-apple-outline", iconSet: "MaterialCommunityIcons" },
    { name: "Tzatziki", emoji: "🥒", icon: "food-egg-easter", iconSet: "MaterialCommunityIcons" },
    { name: "Salsa", emoji: "🍅", icon: "food-fruit-strawberry", iconSet: "MaterialCommunityIcons" },
    { name: "Pesto", emoji: "🌿", icon: "leaf", iconSet: "MaterialCommunityIcons" },
    { name: "Aioli", emoji: "🥚", icon: "egg", iconSet: "MaterialCommunityIcons" },
    { name: "Tahini", emoji: "🌰", icon: "nut", iconSet: "MaterialCommunityIcons" },
    { name: "Harissa", emoji: "🌶️", icon: "pepper", iconSet: "MaterialCommunityIcons" },
    { name: "Fish Sauce", emoji: "🐟", icon: "fish", iconSet: "MaterialCommunityIcons" },
    { name: "Oyster Sauce", emoji: "🦪", icon: "oyster", iconSet: "MaterialCommunityIcons" },
    { name: "Worcestershire Sauce", emoji: "🥣", icon: "food-salt", iconSet: "MaterialCommunityIcons" },
    { name: "Sriracha", emoji: "🌶️", icon: "pepper", iconSet: "MaterialCommunityIcons" },
    { name: "Chimichurri", emoji: "🌿", icon: "leaf", iconSet: "MaterialCommunityIcons" },
    { name: "Gochujang", emoji: "🌶️", icon: "pepper", iconSet: "MaterialCommunityIcons" },
    { name: "Miso", emoji: "🫘", icon: "food-grain", iconSet: "MaterialCommunityIcons" },
  ],
  beverages: [
    { name: "Water", emoji: "💧", icon: "water", iconSet: "MaterialCommunityIcons" },
    { name: "Coffee", emoji: "☕", icon: "coffee", iconSet: "MaterialCommunityIcons" },
    { name: "Tea", emoji: "🍵", icon: "tea", iconSet: "MaterialCommunityIcons" },
    { name: "Milk", emoji: "🥛", icon: "food-egg-easter", iconSet: "MaterialCommunityIcons" },
    { name: "Juice", emoji: "🧃", icon: "food-fruit-grapes", iconSet: "MaterialCommunityIcons" },
    { name: "Wine", emoji: "🍷", icon: "wine-bottle", iconSet: "MaterialCommunityIcons" },
    { name: "Beer", emoji: "🍺", icon: "beer", iconSet: "MaterialCommunityIcons" },
    { name: "Soda", emoji: "🥤", icon: "bottle-soda", iconSet: "MaterialCommunityIcons" },
    { name: "Smoothie", emoji: "🥤", icon: "food-fruit-grapes", iconSet: "MaterialCommunityIcons" },
    { name: "Coconut Water", emoji: "🥥", icon: "coconut-water", iconSet: "MaterialCommunityIcons" },
    { name: "Lassi", emoji: "🥛", icon: "yogurt", iconSet: "MaterialCommunityIcons" },
    { name: "Kombucha", emoji: "🧃", icon: "kombucha", iconSet: "MaterialCommunityIcons" },
    { name: "Matcha", emoji: "🍵", icon: "tea", iconSet: "MaterialCommunityIcons" },
    { name: "Bubble Tea", emoji: "🧋", icon: "bubble-tea", iconSet: "MaterialCommunityIcons" },
    { name: "Hot Chocolate", emoji: "🍫", icon: "hot-chocolate", iconSet: "MaterialCommunityIcons" },
    { name: "Sake", emoji: "🍶", icon: "sake", iconSet: "MaterialCommunityIcons" },
    { name: "Mead", emoji: "🍯", icon: "honey-pot", iconSet: "MaterialCommunityIcons" },
    { name: "Ayran", emoji: "🥛", icon: "yogurt", iconSet: "MaterialCommunityIcons" },
    { name: "Kvass", emoji: "🍞", icon: "bread-slice", iconSet: "MaterialCommunityIcons" },
    { name: "Chicha", emoji: "🍺", icon: "beer", iconSet: "MaterialCommunityIcons" },
  ],
  sweets: [
    { name: "Chocolate", emoji: "🍫", icon: "chocolate-bar", iconSet: "MaterialCommunityIcons" },
    { name: "Candy", emoji: "🍬", icon: "candy", iconSet: "MaterialCommunityIcons" },
    { name: "Cake", emoji: "🍰", icon: "cake-variant", iconSet: "MaterialCommunityIcons" },
    { name: "Cookie", emoji: "🍪", icon: "cookie", iconSet: "MaterialCommunityIcons" },
    { name: "Ice Cream", emoji: "🍨", icon: "ice-cream", iconSet: "MaterialCommunityIcons" },
    { name: "Doughnut", emoji: "🍩", icon: "doughnut", iconSet: "MaterialCommunityIcons" },
    { name: "Pie", emoji: "🥧", icon: "pie", iconSet: "MaterialCommunityIcons" },
    { name: "Pudding", emoji: "🍮", icon: "food-egg-easter", iconSet: "MaterialCommunityIcons" },
    { name: "Baklava", emoji: "🍯", icon: "baklava", iconSet: "MaterialCommunityIcons" },
    { name: "Mochi", emoji: "🍡", icon: "mochi", iconSet: "MaterialCommunityIcons" },
    { name: "Halva", emoji: "🍯", icon: "honey-pot", iconSet: "MaterialCommunityIcons" },
    { name: "Tiramisu", emoji: "🍰", icon: "cake-variant", iconSet: "MaterialCommunityIcons" },
    { name: "Brownie", emoji: "🍫", icon: "cake-variant", iconSet: "MaterialCommunityIcons" },
    { name: "Macaron", emoji: "🍬", icon: "candy", iconSet: "MaterialCommunityIcons" },
    { name: "Churro", emoji: "🍩", icon: "churro", iconSet: "MaterialCommunityIcons" },
    { name: "Pavlova", emoji: "🍰", icon: "cake-variant", iconSet: "MaterialCommunityIcons" },
    { name: "Gelato", emoji: "🍨", icon: "ice-cream", iconSet: "MaterialCommunityIcons" },
    { name: "Rice Pudding", emoji: "🍚", icon: "rice", iconSet: "MaterialCommunityIcons" },
    { name: "Flan", emoji: "🍮", icon: "food-egg-easter", iconSet: "MaterialCommunityIcons" },
    { name: "Jelly", emoji: "🍮", icon: "food-egg-easter", iconSet: "MaterialCommunityIcons" },
    { name: "Fudge", emoji: "🍫", icon: "chocolate-bar", iconSet: "MaterialCommunityIcons" },
    { name: "Nougat", emoji: "🍬", icon: "candy", iconSet: "MaterialCommunityIcons" },
    { name: "Turkish Delight", emoji: "🍬", icon: "candy", iconSet: "MaterialCommunityIcons" },
    { name: "Gulab Jamun", emoji: "��", icon: "gulab-jamun", iconSet: "MaterialCommunityIcons" },
    { name: "Kheer", emoji: "🍚", icon: "rice", iconSet: "MaterialCommunityIcons" },
    { name: "Barfi", emoji: "🍬", icon: "candy", iconSet: "MaterialCommunityIcons" },
    { name: "Kulfi", emoji: "🍨", icon: "ice-cream", iconSet: "MaterialCommunityIcons" },
    { name: "Panna Cotta", emoji: "🍮", icon: "food-egg-easter", iconSet: "MaterialCommunityIcons" },
  ],
  pantry: [
    { name: "Sugar", emoji: "🍚", icon: "sugar-cane", iconSet: "MaterialCommunityIcons" },
    { name: "Brown Sugar", emoji: "🍯", icon: "sugar-cane", iconSet: "MaterialCommunityIcons" },
    { name: "Powdered Sugar", emoji: "🍚", icon: "sugar-cane", iconSet: "MaterialCommunityIcons" },
    { name: "Flour", emoji: "🌾", icon: "sack", iconSet: "MaterialCommunityIcons" },
    { name: "Cornstarch", emoji: "🌽", icon: "corn", iconSet: "MaterialCommunityIcons" },
    { name: "Baking Powder", emoji: "🥄", icon: "bowl-mix", iconSet: "MaterialCommunityIcons" },
    { name: "Baking Soda", emoji: "🥄", icon: "bowl-mix", iconSet: "MaterialCommunityIcons" },
    { name: "Yeast", emoji: "🍞", icon: "bread-slice", iconSet: "MaterialCommunityIcons" },
    { name: "Cocoa Powder", emoji: "🍫", icon: "chocolate-bar", iconSet: "MaterialCommunityIcons" },
    { name: "Vanilla Extract", emoji: "🌱", icon: "leaf", iconSet: "MaterialCommunityIcons" },
    { name: "Vinegar", emoji: "🍶", icon: "vinegar", iconSet: "MaterialCommunityIcons" },
    { name: "Cornmeal", emoji: "🌽", icon: "corn", iconSet: "MaterialCommunityIcons" },
    { name: "Breadcrumbs", emoji: "🍞", icon: "bread-slice", iconSet: "MaterialCommunityIcons" },
    { name: "Gelatin", emoji: "🍮", icon: "food-egg-easter", iconSet: "MaterialCommunityIcons" },
    { name: "Cream of Tartar", emoji: "🥄", icon: "bowl-mix", iconSet: "MaterialCommunityIcons" },
    { name: "Molasses", emoji: "🍯", icon: "honey-pot", iconSet: "MaterialCommunityIcons" },
    { name: "Honey", emoji: "🍯", icon: "honey-pot", iconSet: "MaterialCommunityIcons" },
    { name: "Maple Syrup", emoji: "🍁", icon: "maple-syrup", iconSet: "MaterialCommunityIcons" },
    { name: "Agave", emoji: "🌵", icon: "leaf", iconSet: "MaterialCommunityIcons" },
    // Salt is already present in herbs_and_spices
  ],
};

export default ingredients;
