// Categorized list of ingredients with emojis
// Expanded for global representation

const ingredients = {
  fruits: [
    { name: "Apple", emoji: "🍎" },
    { name: "Banana", emoji: "🍌" },
    { name: "Orange", emoji: "🍊" },
    { name: "Strawberry", emoji: "🍓" },
    { name: "Grapes", emoji: "🍇" },
    { name: "Pineapple", emoji: "🍍" },
    { name: "Watermelon", emoji: "🍉" },
    { name: "Lemon", emoji: "🍋" },
    { name: "Peach", emoji: "🍑" },
    { name: "Mango", emoji: "🥭" },
    { name: "Cherry", emoji: "🍒" },
    { name: "Avocado", emoji: "🥑" },
    { name: "Coconut", emoji: "🥥" },
    { name: "Kiwi", emoji: "🥝" },
    { name: "Blueberry", emoji: "🫐" },
    { name: "Melon", emoji: "🍈" },
    { name: "Pear", emoji: "🍐" },
    { name: "Plum", emoji: "🍑" },
    { name: "Fig", emoji: "🫒" },
    { name: "Pomegranate", emoji: "🍎" },
    { name: "Guava", emoji: "🥝" },
    { name: "Papaya", emoji: "🥭" },
    { name: "Lychee", emoji: "🍒" },
    { name: "Passion Fruit", emoji: "🥭" },
    { name: "Raspberry", emoji: "🍓" },
    { name: "Blackberry", emoji: "🫐" },
    { name: "Cranberry", emoji: "🫐" },
    { name: "Starfruit", emoji: "⭐" },
    { name: "Jackfruit", emoji: "🥭" },
    { name: "Durian", emoji: "🥥" },
    { name: "Dragon Fruit", emoji: "🐉" },
    { name: "Tamarind", emoji: "🌰" },
    { name: "Date", emoji: "🌴" },
    { name: "Soursop", emoji: "🥝" },
    { name: "Longan", emoji: "🍈" },
    { name: "Persimmon", emoji: "🍊" },
    { name: "Mulberry", emoji: "🫐" },
    { name: "Gooseberry", emoji: "🫐" },
    { name: "Currant", emoji: "🫐" },
  ],
  exotic_fruits: [
    { name: "Rambutan", emoji: "🍒" },
    { name: "Salak (Snake Fruit)", emoji: "🥭" },
    { name: "Mangosteen", emoji: "🍈" },
    { name: "Sapote", emoji: "🥭" },
    { name: "Atemoya", emoji: "🍈" },
    { name: "Miracle Fruit", emoji: "🍒" },
    { name: "Jabuticaba", emoji: "🍇" },
    { name: "Ackee", emoji: "🍈" },
    { name: "Breadfruit", emoji: "🍞" },
    { name: "Baobab Fruit", emoji: "🌳" },
    { name: "Horned Melon", emoji: "🍈" },
    { name: "Feijoa", emoji: "🥝" },
    { name: "Cherimoya", emoji: "🍈" },
    { name: "Medlar", emoji: "🍎" },
    { name: "Marang", emoji: "🥭" },
  ],
  vegetables: [
    { name: "Carrot", emoji: "🥕" },
    { name: "Broccoli", emoji: "🥦" },
    { name: "Corn", emoji: "🌽" },
    { name: "Tomato", emoji: "🍅" },
    { name: "Potato", emoji: "🥔" },
    { name: "Cucumber", emoji: "🥒" },
    { name: "Eggplant", emoji: "🍆" },
    { name: "Onion", emoji: "🧅" },
    { name: "Garlic", emoji: "🧄" },
    { name: "Lettuce", emoji: "🥬" },
    { name: "Pepper", emoji: "🫑" },
    { name: "Mushroom", emoji: "🍄" },
    { name: "Sweet Potato", emoji: "🍠" },
    { name: "Chili Pepper", emoji: "🌶️" },
    { name: "Peas", emoji: "🫛" },
    { name: "Okra", emoji: "🫛" },
    { name: "Zucchini", emoji: "🥒" },
    { name: "Radish", emoji: "🌶️" },
    { name: "Turnip", emoji: "🍠" },
    { name: "Artichoke", emoji: "🥬" },
    { name: "Fennel", emoji: "🥬" },
    { name: "Leek", emoji: "🥬" },
    { name: "Celery", emoji: "🥬" },
    { name: "Kale", emoji: "🥬" },
    { name: "Spinach", emoji: "🥬" },
    { name: "Bok Choy", emoji: "🥬" },
    { name: "Daikon", emoji: "🌶️" },
    { name: "Yam", emoji: "🍠" },
    { name: "Cassava", emoji: "🍠" },
    { name: "Jicama", emoji: "🍠" },
    { name: "Taro", emoji: "🍠" },
    { name: "Lotus Root", emoji: "🍠" },
    { name: "Cabbage", emoji: "🥬" },
    { name: "Brussels Sprouts", emoji: "🥦" },
    { name: "Pumpkin", emoji: "🎃" },
    { name: "Squash", emoji: "🎃" },
    { name: "Chayote", emoji: "🥒" },
    { name: "Endive", emoji: "🥬" },
    { name: "Rutabaga", emoji: "🍠" },
  ],
  tubers: [
    { name: "Potato", emoji: "🥔" },
    { name: "Sweet Potato", emoji: "🍠" },
    { name: "Yam", emoji: "🍠" },
    { name: "Cassava", emoji: "🍠" },
    { name: "Taro", emoji: "🍠" },
    { name: "Jicama", emoji: "🍠" },
    { name: "Lotus Root", emoji: "🍠" },
    { name: "Rutabaga", emoji: "🍠" },
    { name: "Parsnip", emoji: "🥕" },
    { name: "Sunchoke", emoji: "🍠" },
  ],
  sea_vegetables: [
    { name: "Nori", emoji: "🌊" },
    { name: "Wakame", emoji: "🌊" },
    { name: "Kombu", emoji: "🌊" },
    { name: "Dulse", emoji: "🌊" },
    { name: "Hijiki", emoji: "🌊" },
    { name: "Sea Lettuce", emoji: "🌊" },
    { name: "Irish Moss", emoji: "🌊" },
  ],
  mushrooms: [
    { name: "Button Mushroom", emoji: "🍄" },
    { name: "Shiitake", emoji: "🍄" },
    { name: "Oyster Mushroom", emoji: "🍄" },
    { name: "Portobello", emoji: "🍄" },
    { name: "Enoki", emoji: "🍄" },
    { name: "Morel", emoji: "🍄" },
    { name: "Chanterelle", emoji: "🍄" },
    { name: "Porcini", emoji: "🍄" },
    { name: "Maitake", emoji: "🍄" },
    { name: "King Oyster", emoji: "🍄" },
    { name: "Truffle", emoji: "🍄" },
  ],
  meats: [
    { name: "Chicken", emoji: "🍗" },
    { name: "Beef", emoji: "🥩" },
    { name: "Pork", emoji: "🍖" },
    { name: "Bacon", emoji: "🥓" },
    { name: "Lamb", emoji: "🍖" },
    { name: "Turkey", emoji: "🦃" },
    { name: "Duck", emoji: "🦆" },
    { name: "Sausage", emoji: "🌭" },
    { name: "Goat", emoji: "🐐" },
    { name: "Rabbit", emoji: "🐇" },
    { name: "Venison", emoji: "🦌" },
    { name: "Quail", emoji: "🐦" },
    { name: "Pigeon", emoji: "🐦" },
    { name: "Kangaroo", emoji: "🦘" },
    { name: "Buffalo", emoji: "🐃" },
    { name: "Camel", emoji: "🐪" },
    { name: "Frog", emoji: "🐸" },
    { name: "Alligator", emoji: "🐊" },
  ],
  seafood: [
    { name: "Fish", emoji: "🐟" },
    { name: "Shrimp", emoji: "🦐" },
    { name: "Crab", emoji: "🦀" },
    { name: "Lobster", emoji: "🦞" },
    { name: "Octopus", emoji: "🐙" },
    { name: "Squid", emoji: "🦑" },
    { name: "Oyster", emoji: "🦪" },
    { name: "Scallop", emoji: "🦪" },
    { name: "Sushi", emoji: "🍣" },
    { name: "Clam", emoji: "🦪" },
    { name: "Mussel", emoji: "🦪" },
    { name: "Anchovy", emoji: "🐟" },
    { name: "Sardine", emoji: "🐟" },
    { name: "Eel", emoji: "🐍" },
    { name: "Caviar", emoji: "🍥" },
    { name: "Sea Urchin", emoji: "🌊" },
    { name: "Abalone", emoji: "🦪" },
  ],
  dairy: [
    { name: "Milk", emoji: "🥛" },
    { name: "Cheese", emoji: "🧀" },
    { name: "Butter", emoji: "🧈" },
    { name: "Yogurt", emoji: "🥣" },
    { name: "Cream", emoji: "🥛" },
    { name: "Egg", emoji: "🥚" },
    { name: "Ice Cream", emoji: "🍨" },
    { name: "Ghee", emoji: "🧈" },
    { name: "Condensed Milk", emoji: "🥛" },
    { name: "Evaporated Milk", emoji: "🥛" },
    { name: "Sour Cream", emoji: "🥛" },
    { name: "Kefir", emoji: "🥛" },
    { name: "Paneer", emoji: "🧀" },
    { name: "Ricotta", emoji: "🧀" },
    { name: "Mascarpone", emoji: "🧀" },
  ],
  cheeses: [
    { name: "Cheddar", emoji: "🧀" },
    { name: "Mozzarella", emoji: "🧀" },
    { name: "Parmesan", emoji: "🧀" },
    { name: "Feta", emoji: "🧀" },
    { name: "Brie", emoji: "🧀" },
    { name: "Camembert", emoji: "🧀" },
    { name: "Gouda", emoji: "🧀" },
    { name: "Swiss", emoji: "🧀" },
    { name: "Blue Cheese", emoji: "🧀" },
    { name: "Goat Cheese", emoji: "🧀" },
    { name: "Halloumi", emoji: "🧀" },
    { name: "Manchego", emoji: "🧀" },
    { name: "Gruyère", emoji: "🧀" },
    { name: "Provolone", emoji: "🧀" },
    { name: "Queso Fresco", emoji: "🧀" },
    { name: "Paneer", emoji: "🧀" },
    { name: "Ricotta", emoji: "🧀" },
    { name: "Mascarpone", emoji: "🧀" },
    { name: "Cottage Cheese", emoji: "🧀" },
  ],
  grains: [
    { name: "Rice", emoji: "🍚" },
    { name: "Bread", emoji: "🍞" },
    { name: "Pasta", emoji: "🍝" },
    { name: "Noodles", emoji: "🍜" },
    { name: "Tortilla", emoji: "🌮" },
    { name: "Oats", emoji: "🌾" },
    { name: "Cornflakes", emoji: "🥣" },
    { name: "Quinoa", emoji: "🌾" },
    { name: "Barley", emoji: "🌾" },
    { name: "Millet", emoji: "🌾" },
    { name: "Buckwheat", emoji: "🌾" },
    { name: "Sorghum", emoji: "🌾" },
    { name: "Rye", emoji: "🌾" },
    { name: "Couscous", emoji: "🍚" },
    { name: "Polenta", emoji: "🍚" },
    { name: "Farro", emoji: "🌾" },
    { name: "Teff", emoji: "🌾" },
    { name: "Freekeh", emoji: "🌾" },
    { name: "Amaranth", emoji: "🌾" },
  ],
  breads: [
    { name: "Baguette", emoji: "🥖" },
    { name: "Sourdough", emoji: "🍞" },
    { name: "Pita", emoji: "🫓" },
    { name: "Naan", emoji: "🫓" },
    { name: "Rye Bread", emoji: "🍞" },
    { name: "Ciabatta", emoji: "🍞" },
    { name: "Focaccia", emoji: "🍞" },
    { name: "Challah", emoji: "🍞" },
    { name: "Brioche", emoji: "🍞" },
    { name: "Cornbread", emoji: "🍞" },
    { name: "Tortilla", emoji: "🌮" },
    { name: "Lavash", emoji: "🫓" },
    { name: "Injera", emoji: "🫓" },
    { name: "Matzo", emoji: "🍞" },
    { name: "Paratha", emoji: "🫓" },
    { name: "Roti", emoji: "🫓" },
    { name: "Bun", emoji: "🍔" },
    { name: "Pretzel", emoji: "🥨" },
    { name: "Bagel", emoji: "🥯" },
  ],
  legumes: [
    { name: "Beans", emoji: "🫘" },
    { name: "Lentils", emoji: "🫘" },
    { name: "Chickpeas", emoji: "🧆" },
    { name: "Peanuts", emoji: "🥜" },
    { name: "Soybeans", emoji: "🫘" },
    { name: "Black Beans", emoji: "🫘" },
    { name: "Kidney Beans", emoji: "🫘" },
    { name: "Navy Beans", emoji: "🫘" },
    { name: "Pinto Beans", emoji: "🫘" },
    { name: "Mung Beans", emoji: "🫘" },
    { name: "Fava Beans", emoji: "🫘" },
    { name: "Lima Beans", emoji: "🫘" },
    { name: "Green Peas", emoji: "🫛" },
    { name: "Split Peas", emoji: "🫛" },
  ],
  nuts_and_seeds: [
    { name: "Almond", emoji: "🌰" },
    { name: "Walnut", emoji: "🌰" },
    { name: "Cashew", emoji: "🥜" },
    { name: "Pistachio", emoji: "🥜" },
    { name: "Sunflower Seeds", emoji: "🌻" },
    { name: "Pumpkin Seeds", emoji: "🎃" },
    { name: "Sesame Seeds", emoji: "🌱" },
    { name: "Hazelnut", emoji: "🌰" },
    { name: "Pecan", emoji: "🌰" },
    { name: "Macadamia", emoji: "🌰" },
    { name: "Pine Nut", emoji: "🌲" },
    { name: "Brazil Nut", emoji: "🌰" },
    { name: "Chestnut", emoji: "🌰" },
    { name: "Chia Seeds", emoji: "🌱" },
    { name: "Flax Seeds", emoji: "🌱" },
    { name: "Hemp Seeds", emoji: "🌱" },
    { name: "Watermelon Seeds", emoji: "🍉" },
  ],
  herbs_and_spices: [
    { name: "Basil", emoji: "🌿" },
    { name: "Parsley", emoji: "🌿" },
    { name: "Cilantro", emoji: "🌿" },
    { name: "Rosemary", emoji: "🌿" },
    { name: "Thyme", emoji: "🌿" },
    { name: "Mint", emoji: "🌿" },
    { name: "Oregano", emoji: "🌿" },
    { name: "Sage", emoji: "🌿" },
    { name: "Cinnamon", emoji: "🌰" },
    { name: "Ginger", emoji: "🫚" },
    { name: "Turmeric", emoji: "🟧" },
    { name: "Pepper", emoji: "🌶️" },
    { name: "Salt", emoji: "🧂" },
    { name: "Chili", emoji: "🌶️" },
    { name: "Clove", emoji: "🌰" },
    { name: "Nutmeg", emoji: "🌰" },
    { name: "Cardamom", emoji: "🌰" },
    { name: "Bay Leaf", emoji: "🌿" },
    { name: "Dill", emoji: "🌿" },
    { name: "Tarragon", emoji: "🌿" },
    { name: "Coriander", emoji: "🌿" },
    { name: "Saffron", emoji: "🧡" },
    { name: "Paprika", emoji: "🌶️" },
    { name: "Curry Leaf", emoji: "🌿" },
    { name: "Fenugreek", emoji: "🌿" },
    { name: "Wasabi", emoji: "🌱" },
    { name: "Galangal", emoji: "🫚" },
    { name: "Star Anise", emoji: "⭐" },
    { name: "Sumac", emoji: "🌿" },
    { name: "Za'atar", emoji: "🌿" },
  ],
  oils_and_fats: [
    { name: "Olive Oil", emoji: "🫒" },
    { name: "Vegetable Oil", emoji: "🛢️" },
    { name: "Coconut Oil", emoji: "🥥" },
    { name: "Butter", emoji: "🧈" },
    { name: "Lard", emoji: "🍖" },
    { name: "Ghee", emoji: "🧈" },
    { name: "Sesame Oil", emoji: "🌱" },
    { name: "Peanut Oil", emoji: "🥜" },
    { name: "Sunflower Oil", emoji: "🌻" },
    { name: "Palm Oil", emoji: "🌴" },
    { name: "Canola Oil", emoji: "🌱" },
    { name: "Avocado Oil", emoji: "🥑" },
    { name: "Corn Oil", emoji: "🌽" },
    { name: "Soybean Oil", emoji: "🫘" },
  ],
  condiments: [
    { name: "Ketchup", emoji: "🍅" },
    { name: "Mayonnaise", emoji: "🥪" },
    { name: "Mustard", emoji: "🌭" },
    { name: "Soy Sauce", emoji: "🥢" },
    { name: "Vinegar", emoji: "🍶" },
    { name: "Hot Sauce", emoji: "🌶️" },
    { name: "Barbecue Sauce", emoji: "🍖" },
    { name: "Honey", emoji: "🍯" },
    { name: "Jam", emoji: "🍓" },
    { name: "Maple Syrup", emoji: "🍁" },
    { name: "Chutney", emoji: "🥣" },
    { name: "Relish", emoji: "🥒" },
    { name: "Tzatziki", emoji: "🥒" },
    { name: "Salsa", emoji: "🍅" },
    { name: "Pesto", emoji: "🌿" },
    { name: "Aioli", emoji: "🥚" },
    { name: "Tahini", emoji: "🌰" },
    { name: "Harissa", emoji: "🌶️" },
    { name: "Fish Sauce", emoji: "🐟" },
    { name: "Oyster Sauce", emoji: "🦪" },
    { name: "Worcestershire Sauce", emoji: "🥣" },
    { name: "Sriracha", emoji: "🌶️" },
    { name: "Chimichurri", emoji: "🌿" },
    { name: "Gochujang", emoji: "🌶️" },
    { name: "Miso", emoji: "🫘" },
  ],
  beverages: [
    { name: "Water", emoji: "💧" },
    { name: "Coffee", emoji: "☕" },
    { name: "Tea", emoji: "🍵" },
    { name: "Milk", emoji: "🥛" },
    { name: "Juice", emoji: "🧃" },
    { name: "Wine", emoji: "🍷" },
    { name: "Beer", emoji: "🍺" },
    { name: "Soda", emoji: "🥤" },
    { name: "Smoothie", emoji: "🥤" },
    { name: "Coconut Water", emoji: "🥥" },
    { name: "Lassi", emoji: "🥛" },
    { name: "Kombucha", emoji: "🧃" },
    { name: "Matcha", emoji: "🍵" },
    { name: "Bubble Tea", emoji: "🧋" },
    { name: "Hot Chocolate", emoji: "🍫" },
    { name: "Sake", emoji: "🍶" },
    { name: "Mead", emoji: "🍯" },
    { name: "Ayran", emoji: "🥛" },
    { name: "Kvass", emoji: "🍞" },
    { name: "Chicha", emoji: "🍺" },
  ],
  sweets: [
    { name: "Chocolate", emoji: "🍫" },
    { name: "Candy", emoji: "🍬" },
    { name: "Cake", emoji: "🍰" },
    { name: "Cookie", emoji: "🍪" },
    { name: "Ice Cream", emoji: "🍨" },
    { name: "Doughnut", emoji: "🍩" },
    { name: "Pie", emoji: "🥧" },
    { name: "Pudding", emoji: "🍮" },
    { name: "Baklava", emoji: "🍯" },
    { name: "Mochi", emoji: "🍡" },
    { name: "Halva", emoji: "🍯" },
    { name: "Tiramisu", emoji: "🍰" },
    { name: "Brownie", emoji: "🍫" },
    { name: "Macaron", emoji: "🍬" },
    { name: "Churro", emoji: "🍩" },
    { name: "Pavlova", emoji: "🍰" },
    { name: "Gelato", emoji: "🍨" },
    { name: "Rice Pudding", emoji: "🍚" },
    { name: "Flan", emoji: "🍮" },
    { name: "Jelly", emoji: "🍮" },
    { name: "Fudge", emoji: "🍫" },
    { name: "Nougat", emoji: "🍬" },
    { name: "Turkish Delight", emoji: "🍬" },
    { name: "Gulab Jamun", emoji: "🍩" },
    { name: "Kheer", emoji: "🍚" },
    { name: "Barfi", emoji: "🍬" },
    { name: "Kulfi", emoji: "🍨" },
    { name: "Panna Cotta", emoji: "🍮" },
  ],
};

export default ingredients;
